#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'xarm-ros2-client-py-pkg','console_scripts','xarm_ros2_client_py'
__requires__ = 'xarm-ros2-client-py-pkg'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('xarm-ros2-client-py-pkg', 'console_scripts', 'xarm_ros2_client_py')()
    )
